### ISSUE TITLE
Schadenswürfe im NonPlayerSheet werfen Fehler 

### ISSUE THREAD

**Issue by Kamufel76** [Thegoodmen/Goodys-DSA-4.1-System#145]
Uncaught TypeError: undefined. element.closest(...).dataset.dmg.toLowerCase.replace is not a function
[Detected 1 package: system:gdsa(0.9.2)]
    at GDSANonPlayerSheet.onNPCDMGRoll (listenerFunctions.js:3065:66)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)
    
   Lösung: in listenerFunctions.js:3065:66 fehlt eine Klammer bei:
       let value = element.closest(".item").dataset.dmg.toLowerCase.replace("w","d"); -->  
       let value = element.closest(".item").dataset.dmg.toLowerCase().replace("w","d")

**Comment by Thegoodmen** [comment]
Fixed
